'use client';

import { useRef, useState } from 'react';
import { Check, FileUp, Link2, Sparkles } from 'lucide-react';

export default function NewWritingPage(){
  const [company,setCompany]=useState('');const [job,setJob]=useState('');const [questions,setQuestions]=useState('');const [fileName,setFileName]=useState('');const [step,setStep]=useState(1);const input=useRef<HTMLInputElement>(null);
  const ready=company.trim()&&job.trim()&&(questions.trim()||fileName);
  return <main className="wizard-v6"><header className="wizard-header-v6"><a href="/writing">← Writing House</a><div><span>새 자기소개서</span><strong>지원 자료 불러오기</strong></div><b>{step} / 2</b></header><section className="wizard-shell-v6"><div className="wizard-title-v6"><span>STEP {step}</span><h1>{step===1?'어디에 지원하나요?':'문항을 확인해 주세요.'}</h1><p>{step===1?'기업과 직무 정보를 먼저 모으면 Archive에서 더 정확한 경험을 추천할 수 있어요.':'파일을 올리거나 직접 입력할 수 있습니다. 나중에 언제든 수정할 수 있어요.'}</p></div>
    {step===1?<div className="source-list-v6"><label><span className="source-num-v6">01</span><div><strong>지원 기업</strong><p>채용 공고의 기업명을 입력하세요.</p></div><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="예: 한국전력거래소"/></label><label><span className="source-num-v6">02</span><div><strong>지원 직무</strong><p>공고에 표시된 직무명을 입력하세요.</p></div><input value={job} onChange={e=>setJob(e.target.value)} placeholder="예: IT"/></label><label><span className="source-num-v6">03</span><div><strong>채용 공고 링크</strong><p>선택 사항 · 나중에 분석할 수 있어요.</p></div><div className="input-with-icon"><Link2/><input placeholder="https://..."/></div></label></div>:<div className="source-list-v6"><section className="question-source-v6"><div><span className="source-num-v6">01</span><strong>자기소개서 문항</strong><p>PDF를 업로드하거나 문항을 직접 붙여 넣으세요.</p></div><div className="source-control-v6"><input ref={input} className="sr-only" type="file" accept=".pdf,.docx,.txt" onChange={e=>setFileName(e.target.files?.[0]?.name||'')}/><button className="dropzone-v6" onClick={()=>input.current?.click()}><FileUp/>{fileName?<><strong>{fileName}</strong><span><Check/> 파일 선택 완료</span></>:<><strong>문항 파일 업로드</strong><span>PDF · DOCX · TXT, 최대 15MB</span></>}</button><span className="or-line">또는 직접 입력</span><textarea value={questions} onChange={e=>setQuestions(e.target.value)} placeholder={'1. 지원 동기를 작성해 주세요. (800자)\n\n2. 협업 경험을 작성해 주세요. (800자)'}/></div></section></div>}
    <footer className="wizard-actions-v6">{step===2&&<button onClick={()=>setStep(1)}>이전 단계</button>}<button className="v6-primary" disabled={step===1?!(company.trim()&&job.trim()):!ready} onClick={()=>step===1?setStep(2):window.location.assign('/writing/editor')}>{step===1?'문항 가져오기':'Archive로 초안 설계'}{step===2&&<Sparkles/>}</button></footer></section></main>;
}
